### ISSUE TITLE
Can´t see the color green when is (+00%), only red (-00%).   

### ISSUE THREAD

**Issue by Tania188** [avocadomaster/cryptowidget#1]
Can´t see the color green "(CODE) .pos color: #66ff66" when the price is (+01%). 
Only red "(CODE) .neg color: #ff6666" is working (-01%) always but without the "-" (01%).

Will be great if the colours change then self on every update.

Thanks 👍

Rest of CODE: 
for value, i in data
    label = ccur[i]
    price = data[i][currency]['PRICE']
    change = data[i][currency]['CHANGEPCT24HOUR']
    state = if (change.charAt(0) == '+') then 'pos' else 'neg'
    if i % 2 == 0
      table.append "<tr/>"
    table.find("tr:last").append renderCurrency(label, price, change, state)
 
<img width="435" alt="captura de pantalla 2017-08-16 a las 16 00 47" src="https://user-images.githubusercontent.com/5273266/29367110-244d46d6-829c-11e7-937a-2f3b2215726a.png">

**Comment by avocadomaster** [comment]
Should be fixed now 👍
